### ISSUE TITLE
Mod assets not loading correctly

### ISSUE THREAD

**Issue by Cesslery** [axialeaa/FlorumSporum#1] opened 2024-06-25 17:18 UTC
I downloaded the latest version of the mod from Modrinth but the Spore blossoms can't be placed correctly, they're always as if hanging from a ceiling. I do have Fabric API as it's required but is there something else required for this mod now?
![2024-06-25_19 14 05](https://github.com/axialeaa/FlorumSporum/assets/114022247/4953febf-4a45-4ffb-9f6d-e2c62827dd3a)
The resource pack doesn't affect it either, tried disabling it and it did the same thing. 
I can try to provide more information if needed.

**Comment by axialeaa** [comment] 2024-06-25 19:33
Thank you for reporting! I have a few questions to get to the bottom of this problem:

- When you move your crosshair over the spore blossom, what does the selection box look like? It should be normal; as if the flower were actually attached to the wall.
- Are you using any other resource pack? If so, please could you provide a list?
- What, if any, mods are you using?
- What version of Fabric API are you using?

This issue is something I faced during development so it's frustrating to see that it's returned. The reason why Fabric API is required is that it automatically loads mod assets when you launch the game, which it seems like is not happening here for some reason. It's not only the block which looks vanilla, the spore blossom in your hotbar should be flipped upside-down! Nothing in the mod resources is loading correctly.

**Comment by Cesslery** [comment] 2024-06-25 19:56
-Yes, the selection bar looks as if it's placed on a wall or on the floor
but it's just turned as if hanging from a ceiling.
-I'm using the Bare Bones resource pack, my own resource pack that only
changes the Bare Bones carpets to have a pattern and azalea leaves to
yellow color, Bare Bones addition that makes the leaves have more detail
instead of being a single color box and authentic shadow. No more resource
packs
-I'm using quite a few mods so the list is gonna be a bit long but they
don't seem like anything that should disrupt your mod.
They are:
ambient Environment 17.0.0.5
Ash API 21.0.0 beta
Bad packets 0.8.1
Big fungus 1.0.0
Cloth config 15.0.127
Collective 1.21.0
Connectible chains 2.4.1
Entityculling 1.6.6
Fabric API 0.100.1+1.21
Fabric language Kotlin 1.11.0+Kotlin 2.0.0
Falling tree 1.21.0.1
ForgeConfigAPIport v21.0.0
Fzzy config 0.3.5
Glowing glow squid 2
GUIclock 1.21.0-4.7
GUIcompass 1.21.0-4.7
Indium 1.0.33
Iris 1.7.1 (though I'm not using any shaders)
Lithium 0.12.5
Modmenu 11.0.0 beta 1
NoLANcheating 1.2
Particle core 0.2.3
Reeses sodium options 1.7.2
Shuffle 21.0.0
Sodium extra 0.5.6
Sodium 0.5.9
Sound physics remastered 1.4.2
Structure music 0.0.6
WTHIT 12.1.2
XaerosWorldMap 1.38.8
YetAnotherConfigLib 3.5.0
All mods are 1.21 versions
Sorry it's quite long but I didn't want to leave any mod out in case it
could be the culprit.

Hope this helps!

**Comment by axialeaa** [comment] 2024-06-25 20:01
That _is_ a long list! Does the issue still occur with just Florum Sporum and Fabric API?

**Comment by Cesslery** [comment] 2024-06-25 20:04
Yes, it unfortunately still does that.
Removed every mod but those two and nothing changed

**Comment by axialeaa** [comment] 2024-06-25 20:16
I'll have a look at my code soon to see if I made a simple mistake, but as long as you have Fabric API (which you do) I cannot fathom why it wouldn't load the assets...

**Comment by Cesslery** [comment] 2024-06-25 20:18
I'm wishing you a smooth fixing. Hope you'll find the cause soon!

**Comment by axialeaa** [comment] 2024-06-26 00:22
I'm afraid I cannot reproduce the issue. I've tried with Florum Sporum 1.2.0+1.21 and both Fabric API 0.100.1+1.21 (the version you had on your client) and 0.100.4+1.21 (the latest version). However, I'm not willing to say it's "unfixable" or "beyond my control" yet as it may have an unreliable/unstable cause that isn't immediately obvious.

 Can you send your log file when you boot up the Florum Sporum + Fabric API instance?

**Comment by Cesslery** [comment] 2024-06-26 00:26
How do I do that exactly? I don't know a lot about this kind of stuff

**Comment by axialeaa** [comment] 2024-06-26 00:35
Oh okay! No worries. Head to your `.minecraft` directory and locate the `logs` folder. I'm looking for a file named `latest.log`.

**Comment by Cesslery** [comment] 2024-06-26 00:38
Okay, thank you, found it~

**Comment by axialeaa** [comment] 2024-06-26 00:54
Wonderful! You should just be able to copy and paste that here.

**Comment by Cesslery** [comment] 2024-06-26 00:56
I sent it, does it not show?
I'll send it again just in case!

**Comment by axialeaa** [comment] 2024-06-26 01:15
It doesn't show, maybe because you're doing it through email?

**Comment by Cesslery** [comment] 2024-06-26 01:18
This should work!
https://drive.google.com/file/d/1vGa71qqVG9ii-wL7hv6naFXnboLOVQmL/view?usp=sharing

**Comment by axialeaa** [comment] 2024-06-26 02:14
The log says that the Florum Sporum assets are loaded, so I honestly don't know where to go from here :/

**Comment by Cesslery** [comment] 2024-06-26 02:52
I noticed you wrote florum sporum 2.0.0, was that a typo or is there a
version 2.0.0? I only have a 1.0.0
Aside from that, I also don't know what is the problem.
I'll try to reinstall the fabric loader after work to see if it could
perhaps fix it somehow. Will let you know if it does~

**Comment by axialeaa** [comment] 2024-06-26 03:21
Sorry, that was a typo. I updated some other mods at a similar time to Florum Sporum. The latest Florum Sporum version is 1.1.0, as you've got already!

**Comment by axialeaa** [comment] 2024-06-26 19:54
Having asked in the Fabric Discord server, a kind user "GravityIO" pointed me to the fact that you may have switched the order of the resource packs in the selector. "Fabric Mods" should be slid above "Default", otherwise the assets in "Default" (the vanilla blockstate, model and texture) will override those in "Fabric Mods".

**Comment by axialeaa** [comment] 2024-06-26 20:04
If that turns out to be the issue, I'll close this as invalid.

**Comment by Cesslery** [comment] 2024-06-26 20:25
I reinstalled the Fabric loader and it still does that so there just has to
be a fault on my side somewhere since everything worked the same for you
and you didn't have the issue replicated.
Probably not gonna be resolved any time soon but I still thank you for your
effort and time!

**Comment by Cesslery** [comment] 2024-06-26 20:33
Oh my god! That solved the issue!
I would've never thought of that as the problem cause.
I'm sorry if this issue solving was a waste of your time but thank you so
much for your help and time!
Wishing you the best~

**Comment by axialeaa** [comment] 2024-06-26 20:34
Not a waste of time at all. I learned something here too! Have a great rest of your day~

**Closed as completed by axialeaa** 2024-06-26 20:34 UTC
Labels: invalid
